### ISSUE TITLE
Python 3.5.1 Build failed in Cygwin

### ISSUE THREAD

**Issue by tcztzy** [pyenv/pyenv#584]
I successfully install Python 2.7.11, but when I try to install Python 3.5.1, some problem came out

```
BUILD FAILED (CYGWIN_NT-10.0-WOW 1.7.35(0.287/5/3) using python-build 20160422)

Inspect or clean up the working tree at /tmp/python-build.20160428011812.848
Results logged to /tmp/python-build.20160428011812.848.log

Last 10 log lines:
./Modules/signalmodule.c:965:5: note: in expansion of macro ‘PyStructSequence_SET_ITEM’
     PyStructSequence_SET_ITEM(result, 6, PyLong_FromLong(si->si_band));
     ^

Makefile:1698: recipe for target 'Modules/signalmodule.o' failed
make: *** [Modules/signalmodule.o] Error 1
make: *** Waiting for unfinished jobs....
./Modules/posixmodule.c: In function ‘posix_initgroups’:
./Modules/posixmodule.c:6272:5: warning: implicit declaration of function ‘initgroups’ [-Wimplicit-function-declaration]
     res = initgroups(username, gid);
     ^
```

I searched at Google before open this issue, I can build Python 3.5.1 in my Cygwin by patch https://bugs.python.org/issue21085.
But I don't know how to patch in pyenv installing. Is there any solutions?
##

**Comment by yyuu** [comment]
Try 'pyenv install -p'. It will read patch from standard input IIRC

**Comment by yyuu** [comment]
Or, you can install the patch as file, like https://github.com/yyuu/pyenv/blob/master/plugins/python-build/share/python-build/patches/3.4.2/Python-3.4.2/010_ssl_no_ssl3.patch

**Comment by tcztzy** [comment]
Sorry, I should RTFM first. Thank you.

**Comment by VShangxiao** [comment]
Oh !  I'm a rookie and I hang on here too!
I wanna know what exactly command I should type in for install Python 3.5.1?
thx !

**Comment by cadyyan** [comment]
@tcztzy, did you have to make any changes to the patch file that you referenced? I've been tearing my hair out trying to get it to work with Python 3.5.1. I made some adjustments but was still seeing failed hunks.

**Comment by tcztzy** [comment]
Finally I gave up cygwin. I cannot understand what the patch really does...so, I quit.

**Comment by cadyyan** [comment]
I've been making some headway on this. I was able to get the first patch to apply properly this morning but quickly ran into another issue which required a patch. Got that one applied as well now I have one more issue (hopefully) to figure out and I should have a working python 3.5.1 build for cygwin. If I can get it working I'll post what I did.

**Comment by cadyyan** [comment]
This is what I have so far.

    wget https://bugs.python.org/file38752/3.4-issue21085-struct_siginfo.patch
    wget https://bugs.python.org/file28934/0001-CYGWIN-issue13756-Python-make-fail-on-cygwin.patch
    cat ./3.4-issue21085-struct_siginfo.patch ./0001-CYGWIN-issue13756-Python-make-fail-on-cygwin.patch | CONFIGURE_OPTS="--with-system-ffi" CFLAGS="-O2" pyenv install --verbose --patch 3.5.1

The first patch is for the OP's original problem. The second patch is to deal with a subsequent issue where `libpython3.5-m.dll` doesn't build. The `CONFIGURE_OPTS` ensures that we use the system's version of FFI since that seems to be an issue (for me at least) as well. The `-O2` is optional but I left it in anyway.

This still results in an error however. I'm not really sure the best way to deal with it so far. I'm not a bash expert so I'm not sure how you could lazily set `PYTHONHOME` to be the correct path. Another patch might be the best option but I'm still evaluating.

    checking how to run the C++ preprocessor... /lib/cpp
    configure: error: in `/tmp/python-build.20160526101014.10464/Python-3.5.1/build/temp.cygwin-1.7.35-i686-3.5/libffi':
    configure: error: C++ preprocessor "/lib/cpp" fails sanity check
    See `config.log' for more details
    
    BUILD FAILED (CYGWIN_NT-10.0-WOW 1.7.35(0.287/5/3) using python-build 20160509-7-g97da7c4)
    
    Inspect or clean up the working tree at /tmp/python-build.20160526101014.10464
    Results logged to /tmp/python-build.20160526101014.10464.log
    
    Last 10 log lines:
        USER_BASE = get_config_var('userbase')
      File "/tmp/python-build.20160526101014.10464/Python-3.5.1/Lib/sysconfig.py", line 582, in get_config_var
        return get_config_vars().get(name)
      File "/tmp/python-build.20160526101014.10464/Python-3.5.1/Lib/sysconfig.py", line 531, in get_config_vars
        _init_posix(_CONFIG_VARS)
      File "/tmp/python-build.20160526101014.10464/Python-3.5.1/Lib/sysconfig.py", line 403, in _init_posix
        from _sysconfigdata import build_time_vars
    ImportError: No module named '_sysconfigdata'
    Makefile:1326: recipe for target 'Lib/plat-cygwin' failed
    make: *** [Lib/plat-cygwin] Error 1

I have confirmed that `_sysconfigdata.py` is built so I'm pretty sure its just that the system dependant librairies are not being used.

**Comment by chrahunt** [comment]
For anyone coming to this issue, note that the patches mentioned in the original comment ([21085](https://bugs.python.org/issue21085)) and the comment by @cadyyan ([13756](https://bugs.python.org/issue13756)) have been merged into CPython as of 3.7. Give this version a try and if you run into any problems (or possible improvements) related to pyenv please create an issue.
