### ISSUE TITLE
Can't add install any Python after upgrade to 2.0

### ISSUE THREAD

**Issue by bolinocroustibat** [pyenv/pyenv#1949]
- Platform information (e.g. Ubuntu Linux 16.04): MacOS 11.3.1
- pyenv version: Pyenv 2.0

When trying to install a Python version, I get the following error log:

```
pyenv install 3.8.10
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.8.10.tar.xz...
-> https://www.python.org/ftp/python/3.8.10/Python-3.8.10.tar.xz
Installing Python-3.8.10...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 11.3.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210526130310.22719
Results logged to /var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210526130310.22719.log

Last 10 log lines:
               ^
./Modules/getpath.c:1192:46: error: expected expression
    calculate->exec_prefix = Py_DecodeLocale(EXEC_PREFIX, &len);
                                             ^
<command line>:5:21: note: expanded from here
#define EXEC_PREFIX "/Users/bolino/.pyenv
                    ^
4 warnings and 2 errors generated.
make: *** [Modules/getpath.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by native-api** [comment]
Please add a debug trace as required by the issue template. It's required for us to be able to do any diagnostic.

**Comment by bolinocroustibat** [comment]
I'm only including here the end of the debug trace of course.

```
		-DSOABI='"cpython-38-darwin"' \
		-o Python/dynload_shlib.o ./Python/dynload_shlib.c
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include   -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include   -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers export/versions/3.8.9/include -I/usr/local/opt/zlib/include  -DPy_BUILD_CORE -o Modules/config.o Modules/config.cadline/include -I/Users/bolino/.pyenvadline/include -I/Users/bolino/.pyenv
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include   -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include   -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers export/versions/3.8.9/include -I/usr/local/opt/zlib/include  -DPy_BUILD_CORE -DPYTHONPATH='""' \/usr/local/opt/readline/include -I/Users/bolino/.pyenvadline/include -I/Users/bolino/.pyenv
export/versions/3.8.9"' \'"/Users/bolino/.pyenv
export/versions/3.8.9"' \EFIX='"/Users/bolino/.pyenv
		-DVERSION='"3.8"' \
		-DVPATH='""' \
		-o Modules/getpath.o ./Modules/getpath.c
warning: macro 'PREFIX' contains embedded newline; text after the newline is ignored
warning: macro 'EXEC_PREFIX' contains embedded newline; text after the newline is ignored
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include   -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include   -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers export/versions/3.8.9/include -I/usr/local/opt/zlib/include  -DPy_BUILD_CORE -o Modules/main.o Modules/main.ct/readline/include -I/Users/bolino/.pyenvadline/include -I/Users/bolino/.pyenv
In file included from <built-in>:368:
<command line>:4:16: warning: missing terminating '"' character [-Winvalid-pp-token]
#define PREFIX "/Users/bolino/.pyenv
               ^
<command line>:5:21: warning: missing terminating '"' character [-Winvalid-pp-token]
#define EXEC_PREFIX "/Users/bolino/.pyenv
                    ^
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include   -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include   -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers export/versions/3.8.9/include -I/usr/local/opt/zlib/include  -DPy_BUILD_CORE -o Modules/gcmodule.o Modules/gcmodule.cne/include -I/Users/bolino/.pyenvadline/include -I/Users/bolino/.pyenv
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include   -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include   -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wsexport/versions/3.8.9/include -I/usr/local/opt/zlib/include  -DPy_BUILD_CORE_BUILTIN  -DPy_BUILD_CORE_BUILTIN -I./Include/internal -c ./Modules/posixmodule.c -o Modules/posixmodule.onv
./Modules/getpath.c:809:49: warning: incompatible pointer types passing 'unsigned long *' to parameter of type 'uint32_t *' (aka 'unsigned int *') [-Wincompatible-pointer-types]
    else if(0 == _NSGetExecutablePath(execpath, &nsexeclength) &&
                                                ^~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/mach-o/dyld.h:98:54: note: passing argument to parameter 'bufsize' here
extern int _NSGetExecutablePath(char* buf, uint32_t* bufsize)                 __OSX_AVAILABLE_STARTING(__MAC_10_2, __IPHONE_2_0);
                                                     ^
./Modules/getpath.c:1192:41: error: expected expression
    calculate->prefix = Py_DecodeLocale(PREFIX, &len);
                                        ^
<command line>:4:16: note: expanded from here
#define PREFIX "/Users/bolino/.pyenv
               ^
./Modules/getpath.c:1196:46: error: expected expression
    calculate->exec_prefix = Py_DecodeLocale(EXEC_PREFIX, &len);
                                             ^
<command line>:5:21: note: expanded from here
#define EXEC_PREFIX "/Users/bolino/.pyenv
                    ^
5 warnings and 2 errors generated.
make: *** [Modules/getpath.o] Error 1
make: *** Waiting for unfinished jobs....
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:749): build_package_standarbuild_failed

+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:126): build_failed(): echo
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:127): build_failed(): colorize 1 'BUILD FAILED'
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:91): colorize(): '[' -t 1 ']'
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:91): colorize(): printf '\e[%sm%s\e[m' 1 'BUILD FAILED'
BUILD FAILED++++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:128): build_failed(): os_information
++++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:97): os_information(): type -p lsb_release
++++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:99): os_information(): type -p sw_vers
+++++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:100): os_information(): sw_vers -productVersion
++++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:100): os_information(): echo 'OS X 11.3.1'
++++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:128): build_failed(): version
++++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:1817): version(): local git_revision
++++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:1819): version(): GIT_DIR=/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/../../../.git
++++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:1819): version(): git remote -v
++++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:1819): version(): grep -q /pyenv
++++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:1823): version(): echo 'python-build 20180424'
 (OS X 11.3.1 using python-build 20180424)

+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:128): build_failed(): echo ' (OS X 11.3.1 using python-build 20180424)'
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:129): build_failed(): echo
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:131): build_failed(): rmdir /var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210527090847.62016
Inspect or clean up the working tree at /var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210527090847.62016
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:132): build_failed(): echo 'Inspect or clean up the working tree at /var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210527090847.62016'
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:134): build_failed(): file_is_not_empty /var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210527090847.62016.log
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:146): file_is_not_empty(): local filename=/var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210527090847.62016.log
++++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:147): file_is_not_empty():wc -l /var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210527090847.62016.log
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:147): file_is_not_empty(): local 'line_count=     987 /var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210527090847.62016.log'
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:149): file_is_not_empty(): '[' -n '     987 /var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210527090847.62016.log' ']'
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:150): file_is_not_empty(): words=($line_count)
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:151): file_is_not_empty(): '[' 987 -gt 0 ']'
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:135): build_failed(): colorize 33 'Results logged to /var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210527090847.62016.log'
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:91): colorize(): '[' -t 1 ']'
Results logged to /var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210527090847.62016.log+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:91): colorize(): printf '\e[%sm%s\e[m' 33 'Results logged to /var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210527090847.62016.log'


+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:136): build_failed(): printf '\n\n'
Last 10 log lines:
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:137): build_failed(): echo 'Last 10 log lines:'
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:138): build_failed(): tail -n 10 /var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210527090847.62016.log
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:147): file_is_not_empty(): local 'line_count=     987 /var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210527090847.62016.log'
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:149): file_is_not_empty(): '[' -n '     987 /var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210527090847.62016.log' ']'
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:150): file_is_not_empty(): words=($line_count)
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:151): file_is_not_empty(): '[' 987 -gt 0 ']'
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:135): build_failed(): colorize 33 'Results logged to /var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210527090847.62016.log'
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:91): colorize(): '[' -t 1 ']'
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:91): colorize(): printf '\e[%sm%s\e[m' 33 'Results logged to /var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210527090847.62016.log'
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:136): build_failed(): printf '\n\n'
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:137): build_failed(): echo 'Last 10 log lines:'
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:138): build_failed(): tail -n 10 /var/folders/cz/6z9410hd6hx05xwjsnx70_4h0000gp/T/python-build.20210527090847.62016.log
+++(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:142): build_failed(): exit 1
+(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/python-build:2184): build_failed(): kill 62046
+(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/pyenv-install:246): STATUS=1
+(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/pyenv-install:249): '[' 1 == 2 ']'
+(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/pyenv-install:277): '[' 1 == 0 ']'
+(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/pyenv-install:280): cleanup
+(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/pyenv-install:239): cleanup(): '[' -z '' ']'
+(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/pyenv-install:239): cleanup(): rm -rf $'/Users/bolino/.pyenv\rexport/versions/3.8.9'
+(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/pyenv-install:283): exit 1
```

**Comment by native-api** [comment]
PYENV_ROOT

> +(/usr/local/Cellar/pyenv/2.0.0/plugins/python-build/bin/pyenv-install:239): cleanup(): rm -rf $'/Users/bolino/.pyenv\rexport/versions/3.8.9'

This suggests that your `PYENV_ROOT` has a `\r` (carriage return symbol) at the end.
It's likely that the file where it's defined has Windows line endings, or you copy-pasted it from somewhere in a way that preserved a Windows line ending.

**Comment by bolinocroustibat** [comment]
@native-api Thanks for your prompt answer. It looks indeed like a syntax problem about PYENV_ROOT in a config file - but can't find where.
Didn't change anything between the switch from 1.2.27 to 2.0.0 so my guess was it comes from MacOS or Pyenv.
When doing `echo $export/bolino/.pyenv` output is `export/bolino/.pyenv` which looks ok,  but doens't tell a lot about line breaks I guess. I'm surprised the env is still available thoughn since I'm doing a full cleanup and removed all pyenv references from .zshrc and .zprofile after uninstalling pyenv.
When doing env it seems PYENV_ROOT is set by zsh. Can't find where.

**Comment by bolinocroustibat** [comment]
Solved. It needed a full restart of the shell to erase all environnement variables (including `PYENV_ROOT`) before reinstalling Pyenv. Thanks to @native-api for the help.
